"""Image generation engine wrapping Antigravity CLI."""

import asyncio
import base64
import logging
import mimetypes
import tempfile
import time
import uuid
from pathlib import Path

from karaagy.config import settings
from karaagy.core.diagnostics import DiagnosticsManager
from karaagy.core.process import get_concurrency_semaphore
from karaagy.core.registry import ModelRegistry
from karaagy.models.openai import ImageGenerationRequest, ImageObject, ImagesResponse

logger = logging.getLogger(__name__)

SUPPORTED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}


def prune_expired_cached_images(max_age_seconds: float | None = None) -> int:
    """Purge cached generated images older than max_age_seconds."""
    max_age = max_age_seconds if max_age_seconds is not None else settings.image_cache_ttl_seconds
    if max_age <= 0:
        return 0

    cache_dir = settings.image_cache_dir
    if not cache_dir.exists() or not cache_dir.is_dir():
        return 0

    now = time.time()
    pruned_count = 0
    for file_path in cache_dir.iterdir():
        if not file_path.is_file():
            continue
        try:
            mtime = file_path.stat().st_mtime
            if now - mtime > max_age:
                file_path.unlink(missing_ok=True)
                pruned_count += 1
                logger.debug(
                    "Pruned expired cached image: %s (age: %.1fs)", file_path.name, now - mtime
                )
        except Exception as e:
            logger.warning("Failed to inspect/prune cached image %s: %s", file_path, e)

    if pruned_count > 0:
        logger.info("Pruned %d expired cached images from %s", pruned_count, cache_dir)
    return pruned_count


async def periodic_image_cache_cleanup_loop(interval_seconds: float = 3600.0) -> None:
    """Background loop to periodically purge expired cached images."""
    while True:
        try:
            await asyncio.sleep(interval_seconds)
            prune_expired_cached_images()
        except asyncio.CancelledError:
            break
        except Exception as e:
            logger.warning("Error in periodic image cache cleanup: %s", e)


async def _generate_single_image(
    prompt_text: str,
    model: str,
    size: str | None = None,
    quality: str | None = None,
    style: str | None = None,
) -> tuple[bytes, str]:
    """Execute agy in an isolated directory to generate a single image and return (bytes, mime_type)."""
    agy_bin = settings.resolve_agy_bin()
    temp_dir_obj = tempfile.TemporaryDirectory(prefix="karaagy_img_gen_")
    temp_dir = Path(temp_dir_obj.name)

    spec_parts = [f"Description: {prompt_text}"]
    if size:
        spec_parts.append(f"Dimensions: {size}")
    if quality:
        spec_parts.append(f"Quality: {quality}")
    if style:
        spec_parts.append(f"Style: {style}")

    generation_prompt = (
        "Generate an image matching this request and save the output image file into the current directory:\n"
        + "\n".join(spec_parts)
    )

    cmd = [
        agy_bin,
        "--dangerously-skip-permissions",
        "--model",
        model,
        "-p",
        generation_prompt,
    ]

    try:
        logger.debug("Executing image generation command in %s: %s", temp_dir, cmd)
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=str(temp_dir),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()

        if proc.returncode != 0:
            error_msg = (
                stderr.decode(errors="replace").strip() or stdout.decode(errors="replace").strip()
            )
            raise RuntimeError(f"Antigravity CLI exited with code {proc.returncode}: {error_msg}")

        # Scan for generated image files
        image_files: list[Path] = []
        for file_path in temp_dir.rglob("*"):
            if file_path.is_file() and file_path.suffix.lower() in SUPPORTED_IMAGE_EXTENSIONS:
                image_files.append(file_path)

        if not image_files:
            out_str = stdout.decode(errors="replace").strip()
            err_str = stderr.decode(errors="replace").strip()
            raise RuntimeError(
                f"No image file was generated by Antigravity CLI. Output: {out_str or err_str or 'empty'}"
            )

        # Pick the most recently created / modified image file
        image_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        selected_file = image_files[0]

        img_bytes = selected_file.read_bytes()
        mime_type, _ = mimetypes.guess_type(str(selected_file))
        if not mime_type:
            mime_type = (
                "image/jpeg" if selected_file.suffix.lower() in {".jpg", ".jpeg"} else "image/png"
            )

        return img_bytes, mime_type
    finally:
        try:
            temp_dir_obj.cleanup()
        except Exception as e:
            logger.warning(
                "Failed to cleanup temporary image generation directory %s: %s", temp_dir, e
            )


async def generate_images(request: ImageGenerationRequest, base_url: str) -> ImagesResponse:
    """Generate images matching OpenAI Images API spec."""
    prompt_clean = request.prompt.strip()
    if not prompt_clean:
        raise ValueError("Parameter 'prompt' cannot be empty.")

    n_count = request.n if request.n is not None else 1
    if n_count < 1 or n_count > 10:
        raise ValueError("Parameter 'n' must be between 1 and 10.")

    if request.model:
        model_name, _ = ModelRegistry.resolve_model_and_effort(request.model, None)
    else:
        model_name = settings.default_model

    semaphore = get_concurrency_semaphore()
    image_objects: list[ImageObject] = []
    settings.image_cache_dir.mkdir(parents=True, exist_ok=True)
    prune_expired_cached_images()

    for _ in range(n_count):
        if semaphore:
            async with semaphore:
                img_bytes, mime_type = await _generate_single_image(
                    prompt_text=prompt_clean,
                    model=model_name,
                    size=request.size,
                    quality=request.quality,
                    style=request.style,
                )
        else:
            img_bytes, mime_type = await _generate_single_image(
                prompt_text=prompt_clean,
                model=model_name,
                size=request.size,
                quality=request.quality,
                style=request.style,
            )

        # Record diagnostics request
        DiagnosticsManager.record_request_completion(
            success=True,
            prompt_tokens=len(prompt_clean.split()),
            completion_tokens=0,
        )

        if request.response_format == "b64_json":
            b64_str = base64.b64encode(img_bytes).decode("utf-8")
            image_objects.append(ImageObject(b64_json=b64_str, revised_prompt=prompt_clean))
        else:
            # Default to url format
            ext = ".jpg" if "jpeg" in mime_type else ".png"
            filename = f"img_{uuid.uuid4().hex[:16]}{ext}"
            target_path = settings.image_cache_dir / filename
            target_path.write_bytes(img_bytes)

            root_url = (settings.public_base_url or base_url).rstrip("/")
            file_url = f"{root_url}/v1/images/files/{filename}"
            image_objects.append(ImageObject(url=file_url, revised_prompt=prompt_clean))

    return ImagesResponse(created=int(time.time()), data=image_objects)
